### PR TITLE
Filter out BGCapture records coming from fakemeter.

### PR DESCRIPTION
**Pull request by alimhassam**
Experimented with modifying openaps.jq to filter out BGCapture records coming from fakemeter.

### CODE REVIEW

**Comment by ecc1** [comment]
Doesn't this only work if the BGReceived records are encountered before the corresponding BGCaptures that we want to filter? Can we rely on this always being the case? And if so, do we even need the array -- wouldn't just the last BGReceived time be enough?

**Comment by alimhassam** [comment]
No I think this traverses the list twice. One to build the array and once to do the original pass. I didn't look at the order of the records. Maybe we can rely on the record orders somehow and do only one pass but I'm not sure how to do that with jq as it's quite hard to keep state.

**Comment by alimhassam** [comment]
Just got this idea, should we set up a unit test case for the openaps.jq file?

**Comment by alimhassam** [comment]
@ecc1 from my personal testing this pr has been working well for me. Let me know if you have additional concerns which need to be  addressed before merging. In my view it's ready to be merged.

I think it would be good to merge it before a next binary release since the other related changes to openAps.jq cause issues with fakemeter.

**Comment by ecc1** [comment]
I've applied this, and added some regression tests in the testdata/ directory for the expected output from the openaps.jq filter that can be checked with "go test".

**Pull request closed without merging**
