### PR TITLE
add exit status for failed upload

### PR DESCRIPTION
**Pull request by juehv**

### CODE REVIEW

**Comment by ecc1** [comment]
Won't this always exit with 1, the somethingFailed case, since that's checked first? Seems to me you have to check uploadFailed first when exiting.

**Comment by juehv** [comment]
That's on purpose! It "something" fails, we probably don't have data, what is the more serious error and we cant loop. If just the upload fails we can continue looping. Since we can just return one value we have to return the most important one. Nobody cares about an upload error if we didn't have data in the first place.

**Comment by ecc1** [comment]
Maybe I missed it, but I never saw a case where uploadFailed was set
without somethingFailed also being set.

**Comment by ecc1** [comment]
Oh, never mind, it's just me not knowing how to read github diffs, and
being color-blind not helping.

**Comment by ecc1** [comment]
Looking at this again, there are several places where the code does log.Fatal(), to exit immediately with an error code (which happens to be 1). Those were cases where it didn't make sense to continue any further (failure to retrieve CGM data, etc.) But they'll also result in no upload, even though the code is the same as "something else". Should I change those to also exit with the uploadFailed status?

**Comment by juehv** [comment]
No I think the more importen information is the failure to retrieve CGM data. I think a reasonable thinking developer is able to guess that no upload happens when no data is retrieved.

**Comment by ecc1** [comment]
I suppose so, but it might require looking at more than just the exit code (like whether the glucose.json file is OK), since those JSON-related failures will have the same exit code as no data retrieved.

Anyway, I will push it as-is and we can always tweak it further.

**Pull request closed without merging**
